# macOS-compatible OpenFold environment
# See README_MACOS.md for detailed installation instructions
# This environment excludes CUDA dependencies and uses CPU/MPS versions
name: openfold-env 
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.10
  - setuptools=59.5.0
  - pip
  - openmm
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - PyYAML
  - requests
  - scipy
  - tqdm
  - typing-extensions
  - wandb
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - git
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
      - deepspeed==0.14.5
      - dm-tree==0.1.6
      - git+https://github.com/NVIDIA/dllogger.git